
services:
  webapi:
    image: leuze_agv_handling_service.webapi
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_URLS: ${ASPNETCORE_URLS}
    ports:
      - "8080:8080"
      - "8081:8081"
