# This Docker Compose is meant to be used for development and local testing purposes

services:
  app:
    image: leuze_agv_handling_service
    platform: linux/arm64
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    ports:
      - "8080:8080"
      - "8081:8081"
    # volumes:
    #   - ./tests/ProcessScripts:/app/ProcessScripts
