version: '3.9'

services:
  webapi:
    image: leuze_agv_handling_service.webapi
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    expose:
      - "8080"
      - "8181"
    ports:
      - "8080:8080"
      - "8081:8081"
