
services:
  app:
    image: leuze_agv_handling_service
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_URLS: ${ASPNETCORE_URLS}
        PROCESS_SCRIPTS_PATH: ${PROCESS_SCRIPTS_PATH}
    ports:
      - "8088:8080"
